map $upstream_response_time $isutools_upstream_response_time {
  "" "-";
  default $upstream_response_time;
}

log_format isutools escape=json
  'method:$request_method'
  '\turi:$uri'
  '\tstatus:$status'
  '\treqtime:$request_time'
  '\tupstime:$isutools_upstream_response_time'
  '\tbytes:$body_bytes_sent'
  '\tcache:$upstream_cache_status'
  '\tctype:$sent_http_content_type'
  '\tproto:$server_protocol'
  '\tsess:$http_x_isutools_session'
  '\tscenario:$http_x_isutools_scenario';

upstream isuride_go {
  server unix:/run/isuride/isuride.sock;
  keepalive 64;
}
