[Service]
Environment=ISUTOOLS_ADDR=127.0.0.1:19196
Environment=ISUTOOLS_DATA_DIR=/home/isucon/isutools-data
Environment=ISUTOOLS_ACCESS_LOG=/home/isucon/isutools-data/nginx-access.log
Environment=ISUTOOLS_ROLE=app
Environment=ISUTOOLS_CPU_PROFILE_MODE=run
Environment=ISUTOOLS_PROFILE_ANALYSIS=1
Environment=ISUTOOLS_GIT_HASH=876bd43a6f6f1048b8d341b2ab62d7afff01efd2
Environment=ISUTOOLS_GIT_DIRTY=1
