[Service]
Environment=ISUTOOLS_FLOW_LABELS=on
Environment=ISUTOOLS_SESSION_COOKIE=SESSIONID
Environment=ISUTOOLS_SCENARIO=isucon13_official
Environment=ISUTOOLS_FLOW_VIZ=on
Environment=ISUTOOLS_FUNNEL_CONFIG=/home/isucon/isutools-config/funnels.yaml
EnvironmentFile=-/etc/isutools/flow-label.env
